[project]
name = "comfyui-lznodes"
description = "Custom nodes for ComfyUI"
version = "1.1.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/liz-ils/ComfyUI-LZNodes"
Documentation = "https://github.com/liz-ils/ComfyUI-LZNodes/wiki"
"Bug Tracker" = "https://github.com/liz-ils/ComfyUI-LZNodes/issues"

[tool.comfy]
PublisherId = "liz-ils"
node_id = "lznodes"
display_name = "ComfyUI-LZNodes"
icon = ""
includes = ["."]